### ISSUE TITLE
maybe a read before assignment problem

### ISSUE THREAD

**Issue by SubOptimal** [javax0/lazylet#2]
Shouldn't it be in the `get()` method of `Sync`
rather be

```
value = (T) supplier.get();
supplied = true;
return value;
```

to avoid a situation like 
threadOne: is assigning `supplied = true;`
threadTwo: find true condition at `if (supplied) {...`
threadTwo: return current value `return value;`
threadOne: assign the value `return value = (T) supplier.get();`

**Comment by verhas** [comment]
You are right. I corrected the code, though it is a bit more complex than what you propose as a fix.

The functionality implicitly defined that `get()` will return null in case the first evaluation threw an exception. Your proposed solution, in this case, would try to call the method `get()` again and again. This could be a possible behavior, but I feel in such a case the code should fix the problem and then go back to the point where the lazy object was created as a retry, it retries are needed at all.

**Comment by verhas** [comment]
1.0.1 relased
